Correções
abc-dev/2017 pull request #3
Opened 2017-08-14 19:15 UTC by khaosdoctor

Correções de CSS

- [x] Alteradas cores do rodapé que não davam para ler 
- [x] Removida borda do bloco 
- [x] Adicionado underline no rodapé para destaque 
- [x] Removido cor duplicada 
- [x] Centralizando texto dentro do wrapper de localização e movendo o mesmo para a direita para não ficar sobre o pin do hotel 
- [x] Removida capacidade de zoom do mapa

Correções no site 

- [x] Corrigido typo com "tomaros" para "tomarmos" 
- [x] Adicionado logo do Google Developers 
- [x] Alterado logo do instagram para colorido ao invés de preto porque todos os outros estavam coloridos

2017-08-15 17:44 UTC, ubirajarapelli commented on src/index.html
> +      <li><a title="Link para o Instagram do ABCDev" href="https://instagram.com/abc-dev"><img src="images/instagram-icon.svg" width="32px" alt="Icone Instagram"></a></li>
Ao retirar do as metas-informações do .SVG, você teve  que colocar estilização no HTML?

2017-08-15 17:46 UTC, ubirajarapelli commented on src/scss/_mixins.scss
> +  -webkit-box-shadow: $x $y $blur rgba(62,50,3,.75);
Desnecessário prefixar, o gulp está fazendo isso no build.

2017-08-15 17:47 UTC, ubirajarapelli commented on src/scss/_mixins.scss
> +  //border: thin solid $light-grey;
Por que retirou a borda do bloco?
E, não seria melhor rmover do que comentar o código?

2017-08-15 17:48 UTC, ubirajarapelli commented on src/scss/style.scss
> +      justify-content: space-around;
Vide comentário sobre prefix acima

2017-08-15 17:49 UTC, ubirajarapelli commented on src/scss/style.scss
> +    pointer-events: none; /* desativa a rolagem com mouse */
Nice!

2017-08-15 17:50 UTC, ubirajarapelli commented on src/scss/style.scss
> +    @include block(25%,0,.9em);}
você verifcou em qual resolução, para fazer a troca de tamaho do bloco?

2017-08-15 17:51 UTC, ubirajarapelli requested changes
Comentários Feitos, por favor revisar

2017-08-16 02:42 UTC, khaosdoctor commented on src/scss/_mixins.scss
> +  -webkit-box-shadow: $x $y $blur rgba(62,50,3,.75);
Meu code faz sozinho quando eu salvo...

2017-08-16 02:43 UTC, khaosdoctor commented on src/index.html
> +      <li><a title="Link para o Instagram do ABCDev" href="https://instagram.com/abc-dev"><img src="images/instagram-icon.svg" width="32px" alt="Icone Instagram"></a></li>
A imagem do SVG é muito grande para a viewbox, não consegui reduzir ela ao tamanho direto pelas metas, tive que combinar os dois

2017-08-16 02:44 UTC, khaosdoctor commented on src/scss/_mixins.scss
> +  //border: thin solid $light-grey;
Nos patrocinadores a borda deixava muito evidente que uma imagem não era do tamanho esperado (tipo a do google), remover a borda deixava menos evidente isso. E parece que fica mais "clean"

2017-08-16 02:44 UTC, khaosdoctor commented on src/scss/style.scss
> +      justify-content: space-around;
Mesma coisa, ele simplesmente completa

2017-08-16 02:45 UTC, khaosdoctor commented on src/scss/style.scss
> +    @include block(25%,0,.9em);}
Sim, ele estava dando erro no tamanho do bloco no meu mac que tem 1200px mais ou menos. Na verdade ele ficava muito pequeno, testei em uma resolução mais larga e ficou bem bacana porque a imagem cresce junto, em uma resolução menor o bloco ocupa 100%

2017-08-16 02:46 UTC, khaosdoctor commented
Vou remover os prefixos

2017-08-24 17:29 UTC, merged

2017-08-24 17:29 UTC, ubirajarapelli commented
@khaosdoctor Não precisar subir outro PR, já resolvi.